In [21]:
import torch

In [22]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Get Data

In [23]:
from src.get_data import get_data

In [24]:
# Pegando os dados

data = get_data()
print(f'{" INPUT ":#^30}')
print(f"{data['input'][:50]}\n")
print('='*30)
print(f'{" TARGET ":#^30}')
print(f"{data['target'][:50]}\n")

########### INPUT ############
Redes Neurais:
16/06/2023
16/06/2020
16/06/2024
16

########### TARGET ###########
Redes Neurais:
16/06/2023

Uma rede neural é um mé



# Tokenizer

In [28]:
from transformers_utils.tokenizer import Tokenizer

In [29]:
tokenizer = Tokenizer()

In [30]:
input_tokens_ids = tokenizer.encode_text_to_id(data['input'])
target_tokens_ids = tokenizer.encode_text_to_id(data['target'])

In [31]:
x = torch.LongTensor(input_tokens_ids).unsqueeze(0)

In [49]:
y = torch.LongTensor(target_tokens_ids).unsqueeze(0)

In [50]:
y

tensor([[ 53,  14,  13,  14,  28,  94,  49,  14,  30,  27,  10,  18,  28,  77,
          96,   1,   6,  76,   0,   6,  76,   2,   0,   2,   3,  96,  96,  56,
          22,  10,  94,  27,  14,  13,  14,  94,  23,  14,  30,  27,  10,  21,
          94,  14,  94,  30,  22,  94,  22,  14,  29,  24,  13,  24,  94,  13,
          14,  94,  18,  23,  29,  14,  21,  18,  16,  14,  23,  12,  18,  10,
          94,  10,  27,  29,  18,  15,  18,  12,  18,  10,  21,  94,  26,  30,
          14,  94,  14,  23,  28,  18,  23,  10,  96,  12,  24,  22,  25,  30,
          29,  10,  13,  24,  27,  14,  28,  94,  10,  94,  25,  27,  24,  12,
          14,  28,  28,  10,  27,  94,  13,  10,  13,  24,  28,  94,  13,  14,
          94,  30,  22,  10,  94,  15,  24,  27,  22,  10,  94,  18,  23,  28,
          25,  18,  27,  10,  13,  10,  94,  25,  14,  21,  24,  94,  12,  14,
          27,  14,  11,  27,  24,  94,  17,  30,  22,  10,  23,  24,  75,  96,
          40,  94,  30,  22,  94,  29,  18,  25,  24

In [32]:
x

tensor([[ 53,  14,  13,  14,  28,  94,  49,  14,  30,  27,  10,  18,  28,  77,
          96,   1,   6,  76,   0,   6,  76,   2,   0,   2,   3,  96,   1,   6,
          76,   0,   6,  76,   2,   0,   2,   0,  96,   1,   6,  76,   0,   6,
          76,   2,   0,   2,   4,  96,   1,   6,  76,   0,   6,  76,   2,   0,
           2,   5,  96,   1,   6,  76,   0,   6,  76,   2,   0,   2,   6,  96,
          96,  96,  96,  56,  22,  10,  94,  27,  14,  13,  14,  94,  23,  14,
          30,  27,  10,  21,  94,  14,  94,  30,  22,  94,  22,  14,  29,  24,
          13,  24,  94,  13,  14,  94,  18,  23,  29,  14,  21,  18,  16,  14,
          23,  12,  18,  10,  94,  10,  27,  29,  18,  15,  18,  12,  18,  10,
          21,  94,  26,  30,  14,  94,  14,  23,  28,  18,  23,  10,  94,  96,
          88,  74,  28,  13,  10,  33,  35,  96,   1,   2,  96,  59,  30,  35,
          96,   3,  96,  96,  96,  96,  96,  12,  24,  22,  25,  30,  29,  10,
          13,  24,  27,  14,  28,  94,  10,  94,  25

In [33]:
x.shape

torch.Size([1, 600])

# Duvida
- Descobrir como treinar o modelo por exemplo eu tenho os tokens [1,2, 1001,1005,1008, 3, 4] como input e os tokens [1,2,3,4] como target, como fazer esse treinamento, os tokens 1001, 1005 e 1008 são sujeiras que quero remover?
- Talvez modelos de resumo sejam assim

# Embedding

In [34]:
from transformers_utils.embeddings import EmbeddingLayer

In [35]:
emb_layer = EmbeddingLayer()

In [36]:
x_emb = emb_layer(x)

In [38]:
x_emb.shape

torch.Size([1, 600, 32])

In [37]:
x_emb

tensor([[[-1.4454,  2.5239,  0.5941,  ...,  0.0378, -1.5960,  0.8048],
         [-0.0175,  1.5512,  0.2503,  ..., -0.5183, -0.2701, -0.0126],
         [-0.1206,  0.1447, -0.3958,  ..., -2.8298,  0.8196,  0.8251],
         ...,
         [ 0.7595,  0.1607,  0.4021,  ..., -0.0989, -0.0031, -1.5912],
         [ 0.7595,  0.1607,  0.4021,  ..., -0.0989, -0.0031, -1.5912],
         [ 0.7595,  0.1607,  0.4021,  ..., -0.0989, -0.0031, -1.5912]]],
       grad_fn=<EmbeddingBackward0>)

# Pos Embedding

In [39]:
# por que usamos Dropout em pos embedding para ele não ficar muito viessado com esse acréscimo de posição?
from transformers_utils.pos_encoding import PositionalEncoding

In [40]:
pos_emb = PositionalEncoding()

In [41]:
x_pos = pos_emb(x_emb)

In [43]:
x_pos.shape

torch.Size([1, 600, 32])

In [42]:
x_pos

tensor([[[-1.4454,  3.5239,  0.5941,  ...,  1.0378, -1.5960,  1.8048],
         [ 0.8240,  2.0915,  0.7835,  ...,  0.4817, -0.2699,  0.9874],
         [ 0.7887, -0.2715,  0.5063,  ..., -1.8298,  0.8200,  1.8251],
         ...,
         [ 0.8567,  1.1559,  0.8214,  ...,  0.8834,  0.1028, -0.5968],
         [ 1.6495,  0.6166,  0.2727,  ...,  0.8833,  0.1030, -0.5968],
         [ 1.6240, -0.3419, -0.2360,  ...,  0.8832,  0.1032, -0.5968]]],
       grad_fn=<AddBackward0>)

# MultiHeadAttention
- sem mask pois queremos olhar para trás e para frente

In [44]:
from transformers_utils.attention import MultiHeadAttention

In [45]:
mult_head_att_layer = MultiHeadAttention()

In [46]:
x_att = mult_head_att_layer(x_pos)

In [48]:
x_att.shape

torch.Size([1, 600, 32])

In [47]:
x_att

tensor([[[ 0.0149,  0.1363, -0.0314,  ...,  0.0142,  0.1397,  0.1267],
         [-0.0010,  0.1357,  0.0071,  ...,  0.0488,  0.1138,  0.1539],
         [ 0.0114,  0.1402, -0.0184,  ...,  0.0205,  0.1171,  0.1460],
         ...,
         [ 0.0224,  0.1426, -0.0183,  ...,  0.0185,  0.1163,  0.1196],
         [ 0.0232,  0.1405, -0.0149,  ...,  0.0173,  0.1146,  0.1153],
         [ 0.0217,  0.1402, -0.0112,  ...,  0.0174,  0.1122,  0.1143]]],
       grad_fn=<TransposeBackward0>)

# Testes aleatorios